name: container-image

outputs:
  ref:
    description: "Container image reference from ko build"
    value: ${{ steps.ko-build.outputs.ref }}

description: "build container image with ko"
runs:
  using: "composite"
  # Defining the action steps(Just one step to be simple)
  steps:
    - uses: actions/setup-go@v4
      with:
        go-version: '1.21.x'
    - uses: ko-build/setup-ko@v0.6
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern=v{{version}}
        flavor: |
          latest=false
    - shell: bash
      run: echo "ref=$(ko build --tags ${{ steps.meta.outputs.tags }}  --bare)" >> "$GITHUB_OUTPUT"
      id: ko-build
